---
name: ntp

releases:
- name: ntp
  version: latest

stemcells:
- alias: ubuntu
  os: ubuntu-xenial
  version: latest

instance_groups:
- name: ntp
  instances: 1
  azs: [ z1 ]
  vm_type: default
  persistent_disk_type: default
  stemcell: ubuntu
  networks:
  - name: default
    static_ips: [ 10.244.0.34 ]
  jobs:
  - name: ntpd
    release: ntp
    properties:
      ntp_conf: |
        server time1.google.com
        server time2.google.com
        server time3.google.com
        restrict default kod nomodify notrap nopeer noquery
        restrict -6 default kod nomodify notrap nopeer noquery
        restrict 127.0.0.0 mask 255.0.0.0
        restrict -6 ::1

update:
  canaries: 1
  max_in_flight: 10
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
